// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPqccIitQmHncBc47lMBUMdtS5Y2BYHNY',
    appId: '1:398425807691:web:4c3dd9b5bbf231e5ebe6ce',
    messagingSenderId: '398425807691',
    projectId: 'terrorflix-app',
    authDomain: 'terrorflix-app.firebaseapp.com',
    storageBucket: 'terrorflix-app.firebasestorage.app',
    databaseURL: 'https://terrorflix-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmQENZcbpnQrQPi0X0TNJjADed2UezCk0',
    appId: '1:398425807691:android:f09d0e49d777b3b6ebe6ce',
    messagingSenderId: '398425807691',
    projectId: 'terrorflix-app',
    storageBucket: 'terrorflix-app.firebasestorage.app',
    databaseURL: 'https://terrorflix-app-default-rtdb.firebaseio.com',
  );
}